import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Linking, Platform, Pressable, StyleSheet, Text, View } from "react-native";

import { GlassCard, Screen, TopBar } from "../components/Glass";
import { radius, useTheme } from "../components/theme";
import licenses from "../config/licenses.json";

// Generated by `npm run licenses` from what actually ships in the bundle.
const ROWS = [
  ...licenses.native.map((lib) => ({ ...lib, key: lib.name, kind: "native" })),
  ...licenses.packages.map((pkg) => ({ ...pkg, key: `${pkg.name}@${pkg.version}`, kind: "js" })),
];

const MONO = Platform.select({ android: "monospace", default: "Menlo" });

export default function Licenses() {
  const t = useTheme();
  return (
    <Screen>
      <TopBar title="Open-source licenses" onBack={() => router.back()} />
      <FlatList
        data={ROWS}
        keyExtractor={(row) => row.key}
        contentContainerStyle={styles.list}
        ListHeaderComponent={
          <Text style={[styles.intro, { color: t.muted }]}>
            EventBetter is open source (MIT) and builds on these projects. Tap one to read its license.
          </Text>
        }
        renderItem={({ item }) => <LicenseRow item={item} />}
        initialNumToRender={20}
      />
    </Screen>
  );
}

function LicenseRow({ item }) {
  const t = useTheme();
  const [open, setOpen] = useState(false);
  const text = item.textId !== undefined ? licenses.texts[item.textId] : null;
  const url = item.url ?? `https://www.npmjs.com/package/${item.name}`;

  return (
    <GlassCard style={styles.card}>
      <Pressable
        accessibilityRole="button"
        accessibilityState={{ expanded: open }}
        onPress={() => (text ? setOpen((o) => !o) : Linking.openURL(url))}
        style={styles.header}
      >
        <View style={styles.titles}>
          <Text style={[styles.name, { color: t.text }]}>{item.name}</Text>
          <Text style={[styles.meta, { color: t.muted }]}>
            {[item.version, item.license].filter(Boolean).join(" · ")}
          </Text>
        </View>
        <Text style={{ color: t.muted, fontSize: 18 }}>{text ? (open ? "▾" : "▸") : "↗"}</Text>
      </Pressable>
      {open && text ? (
        <Text style={[styles.text, { color: t.text, backgroundColor: t.field, borderColor: t.fieldBorder }]}>
          {text}
        </Text>
      ) : null}
    </GlassCard>
  );
}

const styles = StyleSheet.create({
  list: { padding: 12, paddingBottom: 48, gap: 8 },
  intro: { fontSize: 14, lineHeight: 20, marginBottom: 4, paddingHorizontal: 4 },
  card: { paddingVertical: 4, paddingHorizontal: 16 },
  header: { minHeight: 56, flexDirection: "row", alignItems: "center", gap: 8 },
  titles: { flex: 1 },
  name: { fontSize: 15, fontWeight: "600" },
  meta: { fontSize: 13 },
  text: {
    fontFamily: MONO,
    fontSize: 11,
    lineHeight: 16,
    padding: 12,
    marginBottom: 12,
    borderRadius: radius.field,
    borderWidth: 1,
  },
});
